[package]
authors = ["donacrio <donatien.criaud@gmail.com>"]
edition = "2018"
license = "Apache-2.0"
name = "owl"
version = "0.1.0"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[dependencies]

[dev-dependencies]
rstest = "0.6.4"
