name: Continuous integration

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          # - beta
          # - nightly
        # target:
        #   - x86_64-unknown-linux-gnu
        # - x86_64-unknown-linux-musl
        # - x86_64-apple-darwin
        # - x86_64-pc-windows-msvc

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy
      - run: rustup target add x86_64-unknown-linux-gnu && rustup target add x86_64-apple-darwin

      - run: cargo fmt --all --verbose -- --check
      - run: cargo clippy --workspace --all-features --all-targets --verbose -- -D warnings
      - run: cargo build --workspace --all-features --all-targets --verbose
      - run: cargo test --workspace --all-features --all-targets --verbose
