name: Continuous integration

on:
  - push
  - pull_request

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
          - x86_64-apple-darwin
          - x86_64-pc-windows-msvc

    steps:
      - uses: actions/checkout@v2

      - run: sudo apt update && sudo apt install -y build-essential

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
          override: true
          components: rustfmt, clippy

      - run: cargo fmt --all -- --check
      - run: cargo clippy --workspace --verbose -- -D warnings
      - run: cargo build --workspace --verbose
      - run: cargo test --workspace --verbose

      - run: cargo build --workspace --verbose --release
        if: ${{ github.event_name == 'pull_request' }}

      - run: cargo test --workspace --verbose --release
        if: ${{ github.event_name == 'pull_request' }}
