name: Releases

on:
  push:
    branches:
      - master
  pull_request:

env:
  CARGO_TERM_COLOR: always
  BUILDER_IMAGE: sparrow-builder:${{ github.sha }}

jobs:
  build_os_releases:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
          - x86_64-apple-darwin
          - x86_64-pc-windows-msvc
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Update system
        run: sudo apt update && sudo apt install -y build-essential
      -
        name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
          override: true
          components: rustfmt, clippy
      -
        name: Build optimized release binaries
        run: cargo build --workspace --verbose --release
      -
        name: Test optimized release binaries
        run: cargo test --workspace --verbose --release

  build_builder_docker_image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Create .env default config
        run: cp ./default.env ./.env
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Build Sparrow builder image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./dockerfiles/builder.Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ env.BUILDER_IMAGE }}

  build_docker_releases:
    runs-on: ubuntu-latest
    needs: [build_builder_docker_image]
    strategy:
      matrix:
        module_name:
          - sparrow
          - sparrow-cli
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Build Sparrow binaries base image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./dockerfiles/module.Dockerfile
          tags: sparrow/${{ matrix.module_name }}
          build-args: |
            BUILDER_IMAGE=ghcr.io/${{ github.repository_owner }}/${{ env.BUILDER_IMAGE }}
            MODULE_NAME=${{ matrix.module_name }}
